CREATE TABLE IF NOT EXISTS `USERS` (
    `ID_USER` INT NOT NULL AUTO_INCREMENT,
    `EMAIL` VARCHAR(100) NOT NULL,
    `USERNAME` VARCHAR(31) NOT NULL,
    `PASSWORD` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`ID_USER`)
);
