CREATE TABLE IF NOT EXISTS `DOCUMENTS` (
    `ID_DOCUMENT` INT NOT NULL AUTO_INCREMENT,
    `ID_USER` INT NOT NULL,
    `NAME` VARCHAR(255) NOT NULL,
    `URLS` JSON NOT NULL,
    `UPLOADED` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID_DOCUMENT`),
    FOREIGN KEY (`ID_USER`) REFERENCES `USERS`(`ID_USER`) ON DELETE CASCADE
);