CREATE TABLE IF NOT EXISTS `PASSWORDS` (
    `ID_PASSWORD` INT NOT NULL AUTO_INCREMENT,
    `ID_USER` INT NOT NULL,
    `NAME` VARCHAR(255) NOT NULL,
    `PASSWORD` JSON NOT NULL,
    `UPLOADED` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID_PASSWORD`),
    FOREIGN KEY (`ID_USER`) REFERENCES `USERS`(`ID_USER`) ON DELETE CASCADE
);