CREATE TABLE IF NOT EXISTS `IPS` (
    `ID_IP` INT NOT NULL AUTO_INCREMENT,
    `ID_USER` INT NOT NULL,
    `IP` VARCHAR(100) NOT NULL,
    `UPLOADED` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID_IP`),
    FOREIGN KEY (`ID_USER`) REFERENCES `USERS`(`ID_USER`) ON DELETE CASCADE
);