CREATE TABLE IF NOT EXISTS `ENTRIES` (
    `ID_ENTRY` INT NOT NULL AUTO_INCREMENT,
    `ID_USER` INT NOT NULL,
    `IP_ADDRESSES` VARCHAR(100) NOT NULL,
    `UPLOADED` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID_ENTRY`),
    FOREIGN KEY (`ID_USER`) REFERENCES `USERS`(`ID_USER`) ON DELETE CASCADE
);