CREATE TABLE IF NOT EXISTS `ACTIVITIES` (
    `ID_USER` INT NOT NULL,
    `ID_ACTIVITY` INT NOT NULL AUTO_INCREMENT,
    `TEXT` VARCHAR(100) NOT NULL,
    `UPLOADED` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID_ACTIVITY`),
    FOREIGN KEY (`ID_USER`) REFERENCES `USERS`(`ID_USER`) ON DELETE CASCADE
);